
import 'package:flutter/cupertino.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
String docEmail='';
String docName='';
String docPhoneNumber='';
String docUPI='';
TextEditingController docNameController = TextEditingController();
TextEditingController docEmailController = TextEditingController();
TextEditingController docPhoneNumberController = TextEditingController();
TextEditingController docUPIController = TextEditingController();
String? docPhoto;
double? screenWidth;
double? screenHeight;
List<Map<String, String>> daysList = [];
List<Map<String, int>> result = [];
bool editIconVisibility=false;
String dayOfWeek = '';
bool submit= true;
bool formEnabler= true;
bool updateEnabler= false;
double? sizedBoxHeight;
var showCameraIcon= true;
String outputDate2 = '';
String outputDate1 = '';
final formatter = DateFormat('dd-MM-yyyy');
bool isMobileLogin=false;
SharedPreferences? sharedPref;
